[project]
name = "sectorbootstrap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "biopython>=1.86",
    "cocoatree",
    "ete3>=3.1.3",
    "matplotlib>=3.10.8",
    "pandas>=3.0.1",
    "sbm",
    "scikit-learn>=1.8.0",
    "termcolor>=3.3.0",
    "tqdm>=4.67.1",
]

[project.optional-dependencies]
cpu = []
cu124 = []

[tool.uv]
conflicts = [[{extra = "cpu"}, { extra = "cu124" }]]

[tool.uv.sources]
sbm = { git = "https://github.com/StatBio/Stochastic-Boltzmann-Machine" }
cocoatree = { git = "https://github.com/TrEE-TIMC/cocoatree" }

[[tool.uv.index]]
# The pytorch-cpu index is used to install the torch, torchvision, and torchaudio packages
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
